name: Manual Test Execution

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test Suite to Execute'
        required: true
        default: 'regression'
        type: choice
        options:
          - smoke
          - regression
          - full
          - login
          - inventory
          - checkout
      browser:
        description: 'Browser'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
          - edge
      environment:
        description: 'Test Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
          - dev
      parallel_execution:
        description: 'Enable Parallel Execution'
        required: false
        default: true
        type: boolean
      thread_count:
        description: 'Number of parallel threads'
        required: false
        default: '3'

jobs:
  manual-test-execution:
    name: Manual Test Execution
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Install Browser
      run: |
        if [ "${{ github.event.inputs.browser }}" = "chrome" ]; then
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
        elif [ "${{ github.event.inputs.browser }}" = "firefox" ]; then
          sudo apt-get update
          sudo apt-get install -y firefox
        fi
        
    - name: Set Test Tags
      id: set-tags
      run: |
        case "${{ github.event.inputs.test_suite }}" in
          "smoke")
            echo "tags=@smoke" >> $GITHUB_OUTPUT
            ;;
          "login")
            echo "tags=@login" >> $GITHUB_OUTPUT
            ;;
          "inventory")
            echo "tags=@inventory" >> $GITHUB_OUTPUT
            ;;
          "checkout")
            echo "tags=@checkout" >> $GITHUB_OUTPUT
            ;;
          "regression")
            echo "tags=@login or @inventory" >> $GITHUB_OUTPUT
            ;;
          "full")
            echo "tags=not @ignore" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "tags=@login" >> $GITHUB_OUTPUT
            ;;
        esac
        
    - name: Execute Tests
      run: |
        mvn clean test \
          -Dbrowser=${{ github.event.inputs.browser }} \
          -Dheadless=true \
          -Dcucumber.filter.tags="${{ steps.set-tags.outputs.tags }}" \
          -Dparallel.execution=${{ github.event.inputs.parallel_execution }} \
          -Dthread.count=${{ github.event.inputs.thread_count }} \
          -Dtest.environment=${{ github.event.inputs.environment }} \
          -Dmaven.test.failure.ignore=true
      env:
        BROWSER: ${{ github.event.inputs.browser }}
        HEADLESS: true
        TEST_ENVIRONMENT: ${{ github.event.inputs.environment }}
        
    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: manual-test-reports-${{ github.event.inputs.test_suite }}-${{ github.event.inputs.browser }}-${{ github.run_number }}
        path: |
          target/surefire-reports/
          target/cucumber-reports/
          reports/
        retention-days: 30
        
    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: manual-test-screenshots-${{ github.event.inputs.test_suite }}-${{ github.event.inputs.browser }}-${{ github.run_number }}
        path: screenshots/
        retention-days: 15
        
    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: manual-test-logs-${{ github.event.inputs.test_suite }}-${{ github.event.inputs.browser }}-${{ github.run_number }}
        path: logs/
        retention-days: 15
        
    - name: Test Summary
      if: always()
      run: |
        echo "## Test Execution Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Test Suite**: ${{ github.event.inputs.test_suite }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Browser**: ${{ github.event.inputs.browser }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Environment**: ${{ github.event.inputs.environment }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Parallel Execution**: ${{ github.event.inputs.parallel_execution }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Thread Count**: ${{ github.event.inputs.thread_count }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Test Tags**: ${{ steps.set-tags.outputs.tags }}" >> $GITHUB_STEP_SUMMARY 